import { WorldPlot, Furniture } from '../types';

// [Generated by Creator Mode] - 精简并重置了一些基础路边设施，防止错位
export const STREET_PROPS: Furniture[] = [
    {
        "id": "vending_h1",
        "x": 590,
        "y": 490,
        "w": 44,
        "h": 34,
        "color": "#ff5252",
        "label": "可乐贩卖机",
        "utility": "buy_drink",
        "dir": "down",
        "pixelPattern": "vending"
    },
    {
        "id": "vending_h2",
        "x": 640,
        "y": 490,
        "w": 44,
        "h": 34,
        "color": "#4a7dff",
        "label": "矿泉水贩卖机",
        "utility": "buy_drink",
        "dir": "down",
        "pixelPattern": "vending"
    },
    {
        "id": "trash_can_1",
        "x": 1230,
        "y": 490,
        "w": 24,
        "h": 24,
        "color": "#2c3e50",
        "label": "分类垃圾桶",
        "utility": "none",
        "pixelPattern": "trash"
    },
    {
        "id": "tree_1",
        "x": 1870,
        "y": 490,
        "w": 42,
        "h": 42,
        "color": "#253048",
        "label": "梧桐树",
        "utility": "none",
        "pixelPattern": "tree_pixel",
        "pixelOutline": true
    },
    {
        "id": "hydrant_1",
        "x": 1200,
        "y": 1030,
        "w": 18,
        "h": 18,
        "color": "#ff5252",
        "label": "消防栓",
        "utility": "none",
        "pixelOutline": true
    },
];

// 紧凑型网格布局 (4列 x 3行)
// Col X: 60, 700, 1340, 1980
// Row Y: 60, 600, 1140
// 额外功能区在底部 Y=1560
// [更新] 为所有默认地皮指定 customType (用地类型)，防止市民工作/居住逻辑混乱
export const WORLD_LAYOUT: WorldPlot[] = [
    // --- Row 1 (Work & Education) ---
    {
        "id": "plot_dorm",
        "templateId": "dorm",
        "x": 60,
        "y": 60,
        "customType": "residential" // 居住区
    },
    {
        "id": "plot_tech",
        "templateId": "tech",
        "x": 700,
        "y": 60,
        "customType": "work" // 工作区
    },
    {
        "id": "plot_finance",
        "templateId": "finance",
        "x": 1340,
        "y": 60,
        "customType": "work" // 工作区
    },
    {
        "id": "plot_high",
        "templateId": "high_school",
        "x": 1980,
        "y": 60,
        "customType": "public" // 公共/学校
    },

    // --- Row 2 (Living & Leisure) ---
    {
        "id": "plot_apt",
        "templateId": "apartment",
        "x": 60,
        "y": 600,
        "customType": "residential" // 居住区
    },
    {
        "id": "plot_park",
        "templateId": "park",
        "x": 700,
        "y": 600,
        "customType": "public" // 公共休闲
    },
    {
        "id": "plot_comm",
        "templateId": "commercial",
        "x": 1340,
        "y": 600,
        "customType": "commercial" // 商业区
    },
    {
        "id": "plot_elem",
        "templateId": "elementary",
        "x": 1980,
        "y": 600,
        "customType": "public" // 公共/学校
    },

    // --- Row 3 (Service & Nightlife) ---
    {
        "id": "plot_serv",
        "templateId": "service",
        "x": 60,
        "y": 1140,
        "customType": "public" // 公共服务
    },
    {
        "id": "plot_night",
        "templateId": "nightlife",
        "x": 700,
        "y": 1140,
        "customType": "commercial" // 娱乐/商业
    },
    {
        "id": "plot_design",
        "templateId": "design",
        "x": 1340,
        "y": 1140,
        "customType": "work" // 工作区
    },
    {
        "id": "plot_kg",
        "templateId": "kindergarten",
        "x": 1980,
        "y": 1140,
        "customType": "public" // 公共/学校
    },

    // --- Row 4 (Extra / Small) ---
    {
        "id": "plot_netcafe",
        "templateId": "netcafe",
        "x": 60,
        "y": 1560,
        "customType": "commercial" // 商业
    },
    {
        "id": "plot_gallery",
        "templateId": "gallery",
        "x": 700,
        "y": 1560,
        "customType": "public" // 公共文化
    },
    {
        "id": "plot_villa",
        "templateId": "villa",
        "x": 1340,
        "y": 1560,
        "customType": "residential" // 居住区
    },

    // --- Roads (Horizontal) ---
    {
        "id": "road_h1_1", "templateId": "road_h", "x": 0, "y": 480
    },
    {
        "id": "road_h1_2", "templateId": "road_h", "x": 500, "y": 480
    },
    {
        "id": "road_h1_3", "templateId": "road_h", "x": 1000, "y": 480
    },
    {
        "id": "road_h1_4", "templateId": "road_h", "x": 1500, "y": 480
    },
    {
        "id": "road_h1_5", "templateId": "road_h", "x": 2000, "y": 480
    },
    {
        "id": "road_h1_6", "templateId": "road_h", "x": 2500, "y": 480
    },

    {
        "id": "road_h2_1", "templateId": "road_h", "x": 0, "y": 1020
    },
    {
        "id": "road_h2_2", "templateId": "road_h", "x": 500, "y": 1020
    },
    {
        "id": "road_h2_3", "templateId": "road_h", "x": 1000, "y": 1020
    },
    {
        "id": "road_h2_4", "templateId": "road_h", "x": 1500, "y": 1020
    },
    {
        "id": "road_h2_5", "templateId": "road_h", "x": 2000, "y": 1020
    },
    {
        "id": "road_h2_6", "templateId": "road_h", "x": 2500, "y": 1020
    },

    // --- Roads (Vertical) ---
    // V1 @ 580
    { "id": "road_v1_1", "templateId": "road_v", "x": 580, "y": 0 },
    { "id": "road_v1_2", "templateId": "road_v", "x": 580, "y": 500 },
    { "id": "road_v1_3", "templateId": "road_v", "x": 580, "y": 1000 },
    { "id": "road_v1_4", "templateId": "road_v", "x": 580, "y": 1500 },

    // V2 @ 1220
    { "id": "road_v2_1", "templateId": "road_v", "x": 1220, "y": 0 },
    { "id": "road_v2_2", "templateId": "road_v", "x": 1220, "y": 500 },
    { "id": "road_v2_3", "templateId": "road_v", "x": 1220, "y": 1000 },
    { "id": "road_v2_4", "templateId": "road_v", "x": 1220, "y": 1500 },

    // V3 @ 1860
    { "id": "road_v3_1", "templateId": "road_v", "x": 1860, "y": 0 },
    { "id": "road_v3_2", "templateId": "road_v", "x": 1860, "y": 500 },
    { "id": "road_v3_3", "templateId": "road_v", "x": 1860, "y": 1000 },
    { "id": "road_v3_4", "templateId": "road_v", "x": 1860, "y": 1500 },

    // --- Crossings ---
    // Row 1 Intersections
    { "id": "cross_1_1", "templateId": "road_cross", "x": 580, "y": 480 },
    { "id": "cross_1_2", "templateId": "road_cross", "x": 1220, "y": 480 },
    { "id": "cross_1_3", "templateId": "road_cross", "x": 1860, "y": 480 },

    // Row 2 Intersections
    { "id": "cross_2_1", "templateId": "road_cross", "x": 580, "y": 1020 },
    { "id": "cross_2_2", "templateId": "road_cross", "x": 1220, "y": 1020 },
    { "id": "cross_2_3", "templateId": "road_cross", "x": 1860, "y": 1020 },
];