import { WorldPlot, Furniture } from '../types';

// [Generated by Creator Mode]
export const STREET_PROPS: Furniture[] = [
    {
        "id": "vending_h1",
        "x": 940,
        "y": 590,
        "w": 44,
        "h": 34,
        "color": "#ff5252",
        "label": "可乐贩卖机",
        "utility": "buy_drink",
        "dir": "down",
        "pixelPattern": "vending"
    },
    {
        "id": "vending_h2",
        "x": 990,
        "y": 590,
        "w": 44,
        "h": 34,
        "color": "#4a7dff",
        "label": "矿泉水贩卖机",
        "utility": "buy_drink",
        "dir": "down",
        "pixelPattern": "vending"
    },
    {
        "id": "hydrant_1",
        "x": 980,
        "y": 440,
        "w": 18,
        "h": 18,
        "color": "#ff5252",
        "label": "消防栓",
        "utility": "none",
        "pixelOutline": true
    },
    {
        "id": "trash_can_1",
        "x": 1010,
        "y": 440,
        "w": 24,
        "h": 24,
        "color": "#2c3e50",
        "label": "分类垃圾桶",
        "utility": "none",
        "pixelPattern": "trash"
    },
    {
        "id": "custom_1765882114701_d6rhj",
        "x": 2380,
        "y": 430,
        "w": 24,
        "h": 24,
        "color": "#2c3e50",
        "label": "垃圾桶",
        "utility": "none",
        "pixelPattern": "trash"
    },
    {
        "id": "custom_1765882120308_0t315",
        "x": 1000,
        "y": 1290,
        "w": 24,
        "h": 24,
        "color": "#2c3e50",
        "label": "垃圾桶",
        "utility": "none",
        "pixelPattern": "trash"
    },
    {
        "id": "custom_1765882126855_ymlqf",
        "x": 240,
        "y": 1470,
        "w": 42,
        "h": 42,
        "color": "#253048",
        "label": "梧桐树",
        "utility": "none",
        "pixelPattern": "tree_pixel",
        "pixelOutline": true
    },
    {
        "id": "custom_1765882136035_gmri7",
        "x": 2190,
        "y": 2070,
        "w": 42,
        "h": 42,
        "color": "#253048",
        "label": "梧桐树",
        "utility": "none",
        "pixelPattern": "tree_pixel",
        "pixelOutline": true
    },
    {
        "id": "custom_1765882138653_gkkss",
        "x": 2190,
        "y": 2160,
        "w": 42,
        "h": 42,
        "color": "#253048",
        "label": "梧桐树",
        "utility": "none",
        "pixelPattern": "tree_pixel",
        "pixelOutline": true
    },
    {
        "id": "custom_1765882142514_ewxoz",
        "x": 2190,
        "y": 2250,
        "w": 42,
        "h": 42,
        "color": "#253048",
        "label": "梧桐树",
        "utility": "none",
        "pixelPattern": "tree_pixel",
        "pixelOutline": true
    },
    {
        "id": "custom_1765882144670_gn3k5",
        "x": 2190,
        "y": 2350,
        "w": 42,
        "h": 42,
        "color": "#253048",
        "label": "梧桐树",
        "utility": "none",
        "pixelPattern": "tree_pixel",
        "pixelOutline": true
    }
];

export const WORLD_LAYOUT: WorldPlot[] = [
    {
        "id": "plot_tech",
        "templateId": "tech",
        "x": 1210,
        "y": 40
    },
    {
        "id": "plot_finance",
        "templateId": "finance",
        "x": 1730,
        "y": 40
    },
    {
        "id": "plot_design",
        "templateId": "design",
        "x": 2390,
        "y": 70
    },
    {
        "id": "plot_dorm",
        "templateId": "dorm",
        "x": 70,
        "y": 50
    },
    {
        "id": "plot_kg",
        "templateId": "kindergarten",
        "x": 2410,
        "y": 630
    },
    {
        "id": "plot_elem",
        "templateId": "elementary",
        "x": 2840,
        "y": 1830
    },
    {
        "id": "plot_apt",
        "templateId": "apartment",
        "x": 430,
        "y": 650
    },
    {
        "id": "plot_park",
        "templateId": "park",
        "x": 1220,
        "y": 620
    },
    {
        "id": "plot_serv",
        "templateId": "service",
        "x": 310,
        "y": 1470
    },
    {
        "id": "plot_high",
        "templateId": "high_school",
        "x": 2880,
        "y": 610
    },
    {
        "id": "plot_comm",
        "templateId": "commercial",
        "x": 1200,
        "y": 1460
    },
    {
        "id": "plot_night",
        "templateId": "nightlife",
        "x": 2390,
        "y": 1120
    },
    {
        "id": "plot_villa",
        "templateId": "villa",
        "x": 3130,
        "y": 1120
    },
    {
        "id": "plot_netcafe",
        "templateId": "netcafe",
        "x": 10,
        "y": 690
    },
    {
        "id": "plot_gallery",
        "templateId": "gallery",
        "x": 2400,
        "y": 1820
    },
    {
        "id": "road_h1_1",
        "templateId": "road_h",
        "x": 0,
        "y": 480
    },
    {
        "id": "road_h1_2",
        "templateId": "road_h",
        "x": 500,
        "y": 480
    },
    {
        "id": "road_h1_3",
        "templateId": "road_h",
        "x": 1000,
        "y": 480
    },
    {
        "id": "road_h1_4",
        "templateId": "road_h",
        "x": 1500,
        "y": 480
    },
    {
        "id": "road_h1_5",
        "templateId": "road_h",
        "x": 2000,
        "y": 480
    },
    {
        "id": "road_h1_7",
        "templateId": "road_h",
        "x": 2500,
        "y": 480
    },
    {
        "id": "road_h1_8",
        "templateId": "road_h",
        "x": 3000,
        "y": 480
    },
    {
        "id": "road_h2_1",
        "templateId": "road_h",
        "x": 0,
        "y": 1340
    },
    {
        "id": "road_h2_2",
        "templateId": "road_h",
        "x": 500,
        "y": 1340
    },
    {
        "id": "road_h2_3",
        "templateId": "road_h",
        "x": 1000,
        "y": 1340
    },
    {
        "id": "road_h2_4",
        "templateId": "road_h",
        "x": 1500,
        "y": 1340
    },
    {
        "id": "road_h2_5",
        "templateId": "road_h",
        "x": 1790,
        "y": 1340
    },
    {
        "id": "road_h2_7",
        "templateId": "road_h",
        "x": 3330,
        "y": 480
    },
    {
        "id": "road_v1_1",
        "templateId": "road_v",
        "x": 1060,
        "y": 0
    },
    {
        "id": "road_v1_2",
        "templateId": "road_v",
        "x": 1060,
        "y": 580
    },
    {
        "id": "road_v1_3",
        "templateId": "road_v",
        "x": 1060,
        "y": 1080
    },
    {
        "id": "road_v2_1",
        "templateId": "road_v",
        "x": 2260,
        "y": -10
    },
    {
        "id": "road_v2_2",
        "templateId": "road_v",
        "x": 2260,
        "y": 580
    },
    {
        "id": "road_v2_3",
        "templateId": "road_v",
        "x": 2260,
        "y": 1080
    },
    {
        "id": "plot_1765881443454",
        "templateId": "dorm",
        "x": 1260,
        "y": 2070
    },
    {
        "id": "road_custom_1765881929559",
        "templateId": "road_v",
        "x": 2260,
        "y": 1580
    },
    {
        "id": "road_custom_1765881942999",
        "templateId": "road_v",
        "x": 2260,
        "y": 2080
    },
    {
        "id": "road_custom_1765881948051",
        "templateId": "road_cross",
        "x": 2260,
        "y": 1690
    },
    {
        "id": "road_custom_1765881955290",
        "templateId": "road_h",
        "x": 2360,
        "y": 1690
    },
    {
        "id": "road_custom_1765881958521",
        "templateId": "road_h",
        "x": 2860,
        "y": 1690
    },
    {
        "id": "road_custom_1765881961414",
        "templateId": "road_h",
        "x": 3360,
        "y": 1690
    },
    {
        "id": "road_custom_1765881972203",
        "templateId": "road_v",
        "x": 1060,
        "y": 1580
    },
    {
        "id": "road_custom_1765881976176",
        "templateId": "road_v",
        "x": 1060,
        "y": 2080
    },
    {
        "id": "road_custom_1765881998592",
        "templateId": "road_cross",
        "x": 2260,
        "y": 1340
    },
    {
        "id": "road_custom_1765882019029",
        "templateId": "road_cross",
        "x": 1060,
        "y": 1340
    },
    {
        "id": "road_custom_1765882035873",
        "templateId": "road_cross",
        "x": 2260,
        "y": 480
    },
    {
        "id": "road_custom_1765882056753",
        "templateId": "road_cross",
        "x": 1060,
        "y": 480
    }
];
